### ISSUE TITLE
Bug in you project

### ISSUE THREAD

**Issue by Zane96** [mcxtzhang/DiffUtils#3]
@Override
    public boolean areContentsTheSame(int oldItemPosition, int newItemPosition) {
        TestBean beanOld = mOldDatas.get(oldItemPosition);
        TestBean beanNew = mNewDatas.get(newItemPosition);
        if (!beanOld.getDesc().equals(beanNew.getDesc())) {
            return false;//如果有内容不同，就返回false
        }
        if (beanOld.getPic() != beanNew.getPic()) {
            return false;//如果有内容不同，就返回false
        }
        return true; //默认两个data内容是相同的
    }

应该不相同才返回true吧，这样才会继续调用getChangePayload（）方法啊，所以应该默认返回false才对吧。我自己写的demo是跟你相反的

**Comment by mcxtzhang** [comment]
请看方法名：areContentsTheSame  ,以及我博文里的注释，相同返回true，不同返回false。

**Comment by Zane96** [comment]
嗯嗯，我看了下源码是这样的，估计是我的代码写的有问题。谢谢
