### ISSUE TITLE
上拉加载更多

### ISSUE THREAD

**Issue by neochne** [mcxtzhang/DiffUtils#5]
DiffUtil能实现上拉加载更多吗?

**Comment by mcxtzhang** [comment]
DiffUtil是一种工具类，提供数据集之间的差异，它和下拉刷新 上拉加载都不冲突的，属于配合使用的。

**Comment by neochne** [comment]
@mcxtzhang 这个类是怎么在比较啊？我写了个例子，原始数据为：
![image](https://cloud.githubusercontent.com/assets/7844207/19470793/6e3a61f2-9553-11e6-8396-11931ae03875.png)
新数据为：
![image](https://cloud.githubusercontent.com/assets/7844207/19470813/8140de0c-9553-11e6-8310-d2b2e6048746.png)
比较后的结果怎么是这样呢？
![image](https://cloud.githubusercontent.com/assets/7844207/19470841/9c7cce1a-9553-11e6-8fcb-1177eb84b90b.png)

**Comment by mcxtzhang** [comment]
你可参照 http://blog.csdn.net/zxt0601/article/details/52562770 我这篇博文，
根据你贴的这些我无法判断真正的原因
