### ISSUE TITLE
真的很感谢，有两个问题请教一下

### ISSUE THREAD

**Issue by chanchangxing** [mcxtzhang/DiffUtils#6]
这些英文注释看不懂，语法太乱，怎么才能很好的懂他在说什么。

还有这些google出的新的工具的资源在哪里能看得到啊？

感谢感谢

**Comment by mcxtzhang** [comment]
利用翻译软件 ， 这些工具可以关注官网。 我个人的话 其实英文也不是很好，所以我是通过多关注社区论坛 看看最新的消息

**Comment by chanchangxing** [comment]
好的，感谢感谢！
