### ISSUE TITLE
写的很好，不过有个问题想请教一下

### ISSUE THREAD

**Issue by sivan67** [mcxtzhang/DiffUtils#8]
比如我使用的是 `List<Object>`

`Object` 可能是 `BeanA`，`BeanB`，`BeanC` 等等

那我在 `areItemsTheSame(int oldItemPosition, int newItemPosition)` 和 `areContentsTheSame(int oldItemPosition, int newItemPosition)` 这两个方法中该如何判断呢？

**Comment by mcxtzhang** [comment]
instanceof
